clean:
	find . -name "*~" | xargs rm -f
	rstrip.py -R *.txt *.tex *.html *.c *.h *.py *.ma *.gp *akefile README*

# backup the directory to usb, delete useless files
#usb::
#	rsync -avzL --delete-after --exclude="*~" --exclude=".*"  \
#	  * /media/C3/gmxcodenotes/

