#!/bin/bash

# kind of deprecated
if [ $# -lt 2 ] ; then
  echo "require two argument, e.g. put tigger    or get cave"
  exit 1
fi

gmxname=gromacs

if [ $2 = "tigger" ] ; then
  echo "transfer: $1 tigger"
  dest=czhang@tigger.rice.edu:$gmxname
elif [ $2 = "cave" ] ; then
  echo "transfer: $1 cave"
  dest=czhang@10.12.18.201:$gmxname
elif [ $2 == "archive" ] ; then
  echo "transfer: $1 archive"
  dest=../../../archive/${gmxname}4
elif [ $2 == "sugar" ] ; then
  echo "transfer: $1 sugar"
  dest=cz1@sugar.rice.edu:$gmxname
elif [ $2 == "stic" ] ; then
  echo "transfer: $1 stic"
  dest=cz1@stic.rice.edu:$gmxname
elif [ $2 == "ada" ] ; then
  echo "transfer: $1 ada"
  dest=cz1@ada.rice.edu:$gmxname
elif [ $2 == "gpu" ] ; then
  echo "transfer: $1 gpu"
  dest=cz1@badlands.rcsg.rice.edu:$gmxname
elif [ $2 == "bigbend02" ] ; then
  echo "transfer: $1 bigbend02"
  dest=cz1@bigbend02.rice.edu:$gmxname
elif [ $2 == "biou" ] ; then
  echo "transfer: $1 biou"
  dest=cz1@biou.rice.edu:$gmxname
else
  echo "unknown target $2"
  exit 1
fi

src=.
tools="../tools"
mdlib="../mdlib"
gmxlib="../gmxlib"
topol="../../share/top"
if [ $1 = "put" ] ; then
  from="$src/"
  from_tools="$tools/"
  from_mdlib="$mdlib/"
  from_gmxlib="$gmxlib/"
  to="$dest/src/kernel"
  to_tools="$dest/src/tools"
  to_mdlib="$dest/src/mdlib"
  to_gmxlib="$dest/src/gmxlib"
elif [ $1 = "get" ] ; then
  from="$dest/src/kernel/"
  from_tools="$dest/src/tools"
  from_mdlib="$dest/src/mdlib"
  from_gmxlib="$dest/src/gmxlib"
  to="$src"
  to_tools="$tools/"
  to_mdlib="$mdlib/"
  to_gmxlib="$gmxlib/"
else
  echo "unknown action $1"
  exit 1
fi
rsync -avz "$from"{md.c,mdrun.c,bcastmd,bcastmdf,GNUmakefile,Makefile.am,Makefile.in,mkndx2.c,amberize.c,makespx.c,xdihs.c,mqsub.c} "$to"
rsync -avz "$from"{mb_t.0.h,md_tcore.0.h,md_tutil.h,md_t.c,zcom.h} "$to"
rsync -avz "$from"{md1.c,md1core.h,md1util.h,mb1.h,zcom1.h} "$to"
rsync -avz "$from"{md2.c,md2spb.0.h,md2spb.h,md2bb.0.h,md2bb.h,md2core.h,md2util.h,mb2.h,md2conv.c,md2spbx.h} "$to"
